title: Herrera Lab
author: Felipe Herrera
email: felipe.herrera.u@usach.cl
description: > # this means to ignore newlines until "twitter_username:"
 Felipe Herrera Group Website at Universidad de Santiago de Chile.

# social links
twitter_username: faherreraur
github_username:  fherreralab
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - research-areas.md
 - publications.md
 - about.md
 - people.md
 - openings.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
